[versions]
junit = "5.10.1"
strikt = "0.34.0"

[libraries]
junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit"}
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit"}
strikt = { group = "io.strikt", name = "strikt-core", version.ref = "strikt" }
